Repository googlemaps/android-maps-utils, pull requests merged in 2019-10, with the labels that each got.

#542 Update appcompat and core-ktx to 1.1.0
  demo/build.gradle
  demo/gradle.properties
  demo/gradle/wrapper/gradle-wrapper.jar
  demo/gradle/wrapper/gradle-wrapper.properties
  demo/gradlew
  demo/gradlew.bat
  demo/settings.gradle
  library/build.gradle
Labels: cla: yes

#543 publish to staged sonatype repository on tag
  .travis.gpg.enc
  .travis.yml
  gradle-mvn-push.gradle
Labels: cla: yes, semver: patch, type: process

#544 release 0.6.0
  CHANGELOG.md
  REALEASENOTES.md
  gradle-mvn-push.gradle
Labels: cla: yes

#545 Update Android Gradle plugin to 3.5.1
  build.gradle
Labels: cla: yes

#546 add stale config
  .github/stale.yml
Labels: cla: yes

#547 modify stale config
  .github/stale.yml
Labels: cla: yes

#548 modify stale config
  .github/stale.yml
Labels: cla: yes

#549 update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/support_request.md
Labels: cla: yes

#550 Fix test setup
  library/build.gradle
  library/tests/src/com/google/maps/android/clustering/StaticClusterTest.java
  library/tests/src/com/google/maps/android/data/LineStringTest.java
  library/tests/src/com/google/maps/android/data/geojson/GeoJsonLineStringStyleTest.java
  library/tests/src/com/google/maps/android/data/geojson/GeoJsonPointStyleTest.java
  library/tests/src/com/google/maps/android/data/geojson/GeoJsonPolygonStyleTest.java
  library/tests/src/com/google/maps/android/data/kml/KmlContainerParserTest.java
  library/tests/src/com/google/maps/android/data/kml/KmlFeatureParserTest.java
  library/tests/src/com/google/maps/android/data/kml/KmlLineStringTest.java
  library/tests/src/com/google/maps/android/data/kml/KmlParserTest.java
  library/tests/src/com/google/maps/android/data/kml/KmlPointTest.java
  library/tests/src/com/google/maps/android/data/kml/KmlStyleTest.java
  library/tests/src/com/google/maps/android/quadtree/PointQuadTreeTest.java
Labels: cla: yes

#529 Move test resources to test directory.
  library/build.gradle
  library/tests/res/raw/amu_ballon_gx_prefix.kml
  library/tests/res/raw/amu_basic_folder.kml
  library/tests/res/raw/amu_basic_placemark.kml
  library/tests/res/raw/amu_cdata.kml
  library/tests/res/raw/amu_default_balloon.kml
  library/tests/res/raw/amu_document_nest.kml
  library/tests/res/raw/amu_draw_order_ground_overlay.kml
  library/tests/res/raw/amu_extended_data.kml
  library/tests/res/raw/amu_ground_overlay.kml
  library/tests/res/raw/amu_ground_overlay_color.kml
  library/tests/res/raw/amu_inline_style.kml
  library/tests/res/raw/amu_multigeometry_placemarks.kml
  library/tests/res/raw/amu_multiple_placemarks.kml
  library/tests/res/raw/amu_nested_folders.kml
  library/tests/res/raw/amu_nested_multigeometry.kml
  library/tests/res/raw/amu_poly_style_boolean_alpha.kml
  library/tests/res/raw/amu_poly_style_boolean_numeric.kml
  library/tests/res/raw/amu_unknown_folder.kml
  library/tests/res/raw/amu_unsupported.kml
  library/tests/res/raw/amu_visibility_ground_overlay.kml
Labels: cla: yes

#551 add more badges
  README.md
Labels: cla: yes

#552 release 0.6.1
  CHANGELOG.md
  gradle-mvn-push.gradle
Labels: cla: yes

#554 Remove duplicate RegExp components.
  library/src/com/google/maps/android/data/kml/KmlContainerParser.java
  library/src/com/google/maps/android/data/kml/KmlParser.java
Labels: cla: yes

#553 Remove no longer relevant Android API version checks.
  library/src/com/google/maps/android/clustering/ClusterManager.java
  library/src/com/google/maps/android/clustering/view/DefaultClusterRenderer.java
Labels: cla: yes

#555 Change JUnit assertion calls.
  library/tests/src/com/google/maps/android/PolyUtilTest.java
  library/tests/src/com/google/maps/android/clustering/StaticClusterTest.java
  library/tests/src/com/google/maps/android/data/FeatureTest.java
  library/tests/src/com/google/maps/android/data/geojson/BiMultiMapTest.java
  library/tests/src/com/google/maps/android/data/geojson/GeoJsonFeatureTest.java
  library/tests/src/com/google/maps/android/data/geojson/GeoJsonLayerTest.java
  library/tests/src/com/google/maps/android/data/geojson/GeoJsonPointStyleTest.java
  library/tests/src/com/google/maps/android/data/geojson/GeoJsonRendererTest.java
  library/tests/src/com/google/maps/android/data/kml/KmlMultiTrackTest.java
  library/tests/src/com/google/maps/android/data/kml/KmlParserTest.java
  library/tests/src/com/google/maps/android/data/kml/KmlRendererTest.java
  library/tests/src/com/google/maps/android/heatmaps/UtilTest.java
Labels: cla: yes

#557 Remove redundant interface methods public modifier.
  library/src/com/google/maps/android/clustering/Cluster.java
  library/src/com/google/maps/android/data/geojson/GeoJsonStyle.java
  library/src/com/google/maps/android/quadtree/PointQuadTree.java
Labels: cla: yes

#560 Clean up and simplify tests
  library/tests/src/com/google/maps/android/PolyUtilTest.java
  library/tests/src/com/google/maps/android/SphericalUtilTest.java
  library/tests/src/com/google/maps/android/clustering/QuadItemTest.java
  library/tests/src/com/google/maps/android/clustering/StaticClusterTest.java
  library/tests/src/com/google/maps/android/data/FeatureTest.java
  library/tests/src/com/google/maps/android/data/LineStringTest.java
  library/tests/src/com/google/maps/android/data/MultiGeometryTest.java
  library/tests/src/com/google/maps/android/data/PointTest.java
  library/tests/src/com/google/maps/android/data/RendererTest.java
  library/tests/src/com/google/maps/android/data/geojson/BiMultiMapTest.java
  library/tests/src/com/google/maps/android/data/geojson/GeoJsonFeatureTest.java
  library/tests/src/com/google/maps/android/data/geojson/GeoJsonLayerTest.java
  library/tests/src/com/google/maps/android/data/geojson/GeoJsonLineStringStyleTest.java
  library/tests/src/com/google/maps/android/data/geojson/GeoJsonLineStringTest.java
  library/tests/src/com/google/maps/android/data/geojson/GeoJsonMultiLineStringTest.java
  library/tests/src/com/google/maps/android/data/geojson/GeoJsonMultiPointTest.java
  library/tests/src/com/google/maps/android/data/geojson/GeoJsonMultiPolygonTest.java
  library/tests/src/com/google/maps/android/data/geojson/GeoJsonParserTest.java
  library/tests/src/com/google/maps/android/data/geojson/GeoJsonPointStyleTest.java
  library/tests/src/com/google/maps/android/data/geojson/GeoJsonPointTest.java
  library/tests/src/com/google/maps/android/data/geojson/GeoJsonPolygonStyleTest.java
  library/tests/src/com/google/maps/android/data/geojson/GeoJsonPolygonTest.java
  library/tests/src/com/google/maps/android/data/geojson/GeoJsonRendererTest.java
  library/tests/src/com/google/maps/android/data/kml/KmlContainerParserTest.java
  library/tests/src/com/google/maps/android/data/kml/KmlFeatureParserTest.java
  library/tests/src/com/google/maps/android/data/kml/KmlLineStringTest.java
  library/tests/src/com/google/maps/android/data/kml/KmlMultiGeometryTest.java
  library/tests/src/com/google/maps/android/data/kml/KmlMultiTrackTest.java
  library/tests/src/com/google/maps/android/data/kml/KmlParserTest.java
  library/tests/src/com/google/maps/android/data/kml/KmlPointTest.java
  library/tests/src/com/google/maps/android/data/kml/KmlPolygonTest.java
  library/tests/src/com/google/maps/android/data/kml/KmlRendererTest.java
  library/tests/src/com/google/maps/android/data/kml/KmlStyleTest.java
  library/tests/src/com/google/maps/android/data/kml/KmlTrackTest.java
  library/tests/src/com/google/maps/android/heatmaps/GradientTest.java
  library/tests/src/com/google/maps/android/heatmaps/UtilTest.java
  library/tests/src/com/google/maps/android/quadtree/PointQuadTreeTest.java
Labels: cla: yes

#565 add pr templates
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: cla: yes

#563 Remove apklib publishing
  .travis.yml
  gradle-mvn-push.gradle
Labels: cla: yes, triage me

#483 Use float zoom to calculate visible bounds
  library/src/main/java/com/google/maps/android/clustering/algo/Algorithm.java
  library/src/main/java/com/google/maps/android/clustering/algo/GridBasedAlgorithm.java
  library/src/main/java/com/google/maps/android/clustering/algo/NonHierarchicalDistanceBasedAlgorithm.java
  library/src/main/java/com/google/maps/android/clustering/algo/NonHierarchicalViewBasedAlgorithm.java
  library/src/main/java/com/google/maps/android/clustering/algo/PreCachingAlgorithmDecorator.java
  library/src/main/java/com/google/maps/android/clustering/algo/ScreenBasedAlgorithmAdapter.java
Labels: cla: yes, triage me

#499 Expose MaxIntensity functionality to user
  library/src/main/java/com/google/maps/android/heatmaps/HeatmapTileProvider.java
Labels: cla: yes, semver: minor

#566 Update Gradle wrapper to 5.6.3
  gradle/wrapper/gradle-wrapper.properties
Labels: cla: yes

#564 Handle wrapping around international date line
  library/src/main/java/com/google/maps/android/clustering/algo/NonHierarchicalViewBasedAlgorithm.java
Labels: cla: yes, triage me

#567 Differentiate between initial start and configuration change restore
  demo/src/main/java/com/google/maps/android/utils/demo/BaseDemoActivity.java
  demo/src/main/java/com/google/maps/android/utils/demo/BigClusteringDemoActivity.java
  demo/src/main/java/com/google/maps/android/utils/demo/ClusteringDemoActivity.java
  demo/src/main/java/com/google/maps/android/utils/demo/CustomMarkerClusteringDemoActivity.java
  demo/src/main/java/com/google/maps/android/utils/demo/DistanceDemoActivity.java
  demo/src/main/java/com/google/maps/android/utils/demo/GeoJsonDemoActivity.java
  demo/src/main/java/com/google/maps/android/utils/demo/HeatmapsDemoActivity.java
  demo/src/main/java/com/google/maps/android/utils/demo/HeatmapsPlacesDemoActivity.java
  demo/src/main/java/com/google/maps/android/utils/demo/IconGeneratorDemoActivity.java
  demo/src/main/java/com/google/maps/android/utils/demo/KmlDemoActivity.java
  demo/src/main/java/com/google/maps/android/utils/demo/PolyDecodeDemoActivity.java
  demo/src/main/java/com/google/maps/android/utils/demo/PolySimplifyDemoActivity.java
  demo/src/main/java/com/google/maps/android/utils/demo/TileProviderAndProjectionDemo.java
  demo/src/main/java/com/google/maps/android/utils/demo/VisibleClusteringDemoActivity.java
Labels: cla: yes, triage me

#568 Release 0.6.2
  CHANGELOG.md
  gradle-mvn-push.gradle
  gradle.properties
Labels: cla: yes

#569 Change test methods visibility
  library/src/androidTest/java/com/google/maps/android/clustering/QuadItemTest.java
  library/src/androidTest/java/com/google/maps/android/data/MultiGeometryTest.java
  library/src/androidTest/java/com/google/maps/android/data/RendererTest.java
  library/src/androidTest/java/com/google/maps/android/data/geojson/GeoJsonLayerTest.java
  library/src/androidTest/java/com/google/maps/android/data/geojson/GeoJsonLineStringStyleTest.java
  library/src/androidTest/java/com/google/maps/android/data/geojson/GeoJsonLineStringTest.java
  library/src/androidTest/java/com/google/maps/android/data/geojson/GeoJsonMultiLineStringTest.java
  library/src/androidTest/java/com/google/maps/android/data/geojson/GeoJsonMultiPointTest.java
  library/src/androidTest/java/com/google/maps/android/data/geojson/GeoJsonMultiPolygonTest.java
  library/src/androidTest/java/com/google/maps/android/data/geojson/GeoJsonParserTest.java
  library/src/androidTest/java/com/google/maps/android/data/geojson/GeoJsonPointStyleTest.java
  library/src/androidTest/java/com/google/maps/android/data/geojson/GeoJsonPolygonStyleTest.java
  library/src/androidTest/java/com/google/maps/android/data/geojson/GeoJsonPolygonTest.java
  library/src/androidTest/java/com/google/maps/android/data/geojson/GeoJsonRendererTest.java
  library/src/androidTest/java/com/google/maps/android/data/kml/KmlMultiGeometryTest.java
Labels: cla: yes

#571 Fix #532 - Use ContextCompat to load drawable resources for scaling
  library/src/main/java/com/google/maps/android/ui/BubbleDrawable.java
  library/src/main/java/com/google/maps/android/ui/IconGenerator.java
Labels: cla: yes
