Repository googlemaps/android-maps-utils, pull requests merged in 2019-11, with the labels that each got.

#576 Fix #575 - Use API 26 emulator instead of API 28
  .travis.yml
Labels: cla: yes

#574 Bump Gradle plugin for Android Studio v3.5.2
  build.gradle
Labels: cla: yes

#581 Fix #570 - Use project GitHub URL for remote KML loading demo
  demo/src/main/res/values/strings.xml
Labels: cla: yes

#492 Made GeoJsonParser with parseGeometry public to use parser standalone
  library/src/main/java/com/google/maps/android/data/geojson/GeoJsonParser.java
Labels: cla: yes, priority: p1

#381 Retain the bitmap cache
  demo/src/main/java/com/google/maps/android/utils/demo/KmlDemoActivity.java
  library/src/main/java/com/google/maps/android/data/Renderer.java
  library/src/main/java/com/google/maps/android/data/kml/KmlLayer.java
  library/src/main/java/com/google/maps/android/data/kml/KmlRenderer.java
Labels: cla: yes, priority: p1, semver: major

#585 Fix #575 - Change Travis config, use matrix of API emulators
  .travis.yml
  gradle.properties
  library/build.gradle
  library/src/androidTest/java/com/google/maps/android/TestUtil.java
  library/src/androidTest/java/com/google/maps/android/data/geojson/GeoJsonPointStyleTest.java
  library/src/androidTest/java/com/google/maps/android/heatmaps/GradientTest.java
  library/src/androidTest/java/com/google/maps/android/quadtree/PointQuadTreeTest.java
  tools/android-wait-for-emulator.sh
Labels: cla: yes

#586 Remove unnecessary primitives boxing.
  library/src/main/java/com/google/maps/android/data/kml/KmlFeatureParser.java
  library/src/main/java/com/google/maps/android/data/kml/KmlStyleParser.java
Labels: cla: yes

#587 Remove unnecessary interface method public modifiers.
  library/src/main/java/com/google/maps/android/data/Geometry.java
Labels: cla: yes
