Repository googlemaps/android-maps-utils, pull requests merged in 2020-01, with the labels that each got.

#597 fix: increase stale bot window
  .github/stale.yml
Labels: cla: yes

#600 Fix #530 - Check for empty KML Style <hotspot> element before parsing
  library/src/androidTest/java/com/google/maps/android/data/kml/KmlParserTest.java
  library/src/androidTest/res/raw/amu_empty_hotspot.kml
  library/src/main/java/com/google/maps/android/data/kml/KmlStyleParser.java
Labels: cla: yes

#599 Fix #427 - Trim leading/trailing whitespace in KML colors
  library/src/androidTest/java/com/google/maps/android/data/kml/KmlStyleTest.java
  library/src/main/java/com/google/maps/android/data/kml/KmlStyle.java
Labels: cla: yes

#601 Use thread pools
  library/src/main/java/com/google/maps/android/clustering/algo/PreCachingAlgorithmDecorator.java
  library/src/main/java/com/google/maps/android/clustering/view/DefaultClusterRenderer.java
Labels: cla: yes

#349 Fix #519 - PolyUtil.distanceToLine() result
  library/src/androidTest/java/com/google/maps/android/PolyUtilTest.java
  library/src/main/java/com/google/maps/android/PolyUtil.java
Labels: cla: yes, priority: p1

#602 docs(Template): update location of PR template
  .github/pull_request_template.md
Labels: cla: yes

#604 Make QuadItem protected
  library/src/main/java/com/google/maps/android/clustering/algo/NonHierarchicalDistanceBasedAlgorithm.java
Labels: cla: yes

#380 Add MapObjectManager for multi-layer support with KML/GeoJSON renderers
  build.gradle
  library/src/androidTest/java/com/google/maps/android/data/RendererTest.java
  library/src/androidTest/java/com/google/maps/android/data/geojson/GeoJsonRendererTest.java
  library/src/androidTest/java/com/google/maps/android/data/kml/KmlRendererTest.java
  library/src/main/java/com/google/maps/android/clustering/ClusterManager.java
  library/src/main/java/com/google/maps/android/clustering/view/DefaultClusterRenderer.java
  library/src/main/java/com/google/maps/android/collections/CircleManager.java
  library/src/main/java/com/google/maps/android/collections/GroundOverlayManager.java
  library/src/main/java/com/google/maps/android/collections/MapObjectManager.java
  library/src/main/java/com/google/maps/android/collections/MarkerManager.java
  library/src/main/java/com/google/maps/android/collections/PolygonManager.java
  library/src/main/java/com/google/maps/android/collections/PolylineManager.java
  library/src/main/java/com/google/maps/android/data/Layer.java
  library/src/main/java/com/google/maps/android/data/Renderer.java
  library/src/main/java/com/google/maps/android/data/geojson/GeoJsonLayer.java
  library/src/main/java/com/google/maps/android/data/geojson/GeoJsonRenderer.java
  library/src/main/java/com/google/maps/android/data/kml/KmlLayer.java
  library/src/main/java/com/google/maps/android/data/kml/KmlRenderer.java
Labels: cla: yes, priority: p1, semver: major

#588 Move tests to JVM where possible.
  library/src/test/java/com/google/maps/android/PolyUtilTest.java
  library/src/test/java/com/google/maps/android/SphericalUtilTest.java
  library/src/test/java/com/google/maps/android/clustering/QuadItemTest.java
  library/src/test/java/com/google/maps/android/clustering/StaticClusterTest.java
  library/src/test/java/com/google/maps/android/data/FeatureTest.java
  library/src/test/java/com/google/maps/android/data/LineStringTest.java
  library/src/test/java/com/google/maps/android/data/MultiGeometryTest.java
  library/src/test/java/com/google/maps/android/data/PointTest.java
  library/src/test/java/com/google/maps/android/data/RendererTest.java
  library/src/test/java/com/google/maps/android/data/geojson/BiMultiMapTest.java
  library/src/test/java/com/google/maps/android/data/geojson/GeoJsonLineStringTest.java
  library/src/test/java/com/google/maps/android/data/geojson/GeoJsonMultiLineStringTest.java
  library/src/test/java/com/google/maps/android/data/geojson/GeoJsonMultiPointTest.java
  library/src/test/java/com/google/maps/android/data/geojson/GeoJsonMultiPolygonTest.java
  library/src/test/java/com/google/maps/android/data/geojson/GeoJsonPointTest.java
  library/src/test/java/com/google/maps/android/data/geojson/GeoJsonPolygonTest.java
  library/src/test/java/com/google/maps/android/data/kml/KmlLineStringTest.java
  library/src/test/java/com/google/maps/android/data/kml/KmlMultiGeometryTest.java
  library/src/test/java/com/google/maps/android/data/kml/KmlMultiTrackTest.java
  library/src/test/java/com/google/maps/android/data/kml/KmlPointTest.java
  library/src/test/java/com/google/maps/android/data/kml/KmlPolygonTest.java
  library/src/test/java/com/google/maps/android/data/kml/KmlRendererTest.java
  library/src/test/java/com/google/maps/android/data/kml/KmlTrackTest.java
  library/src/test/java/com/google/maps/android/quadtree/PointQuadTreeTest.java
Labels: cla: yes, priority: p2

#611 docs(Code of Conduct): adding CODE_OF_CONDUCT.md file.
  CODE_OF_CONDUCT.md
Labels: cla: yes

#598 Add a new demo activity that tests multiple layers on same map
  demo/src/main/AndroidManifest.xml
  demo/src/main/java/com/google/maps/android/utils/demo/MainActivity.java
  demo/src/main/java/com/google/maps/android/utils/demo/MultiLayerDemoActivity.java
  demo/src/main/res/raw/south_london_line_geojson.json
  demo/src/main/res/raw/south_london_line_kml.kml
  demo/src/main/res/raw/south_london_square_geojson.json
  demo/src/main/res/raw/south_london_square_kml.kml
Labels: cla: yes

#612 docs(CHANGELOG): Adding link in CHANGELOG to unreleased changes.
  CHANGELOG.md
Labels: cla: yes

#603 Use MarkerCache for cluster markers
  library/src/main/java/com/google/maps/android/clustering/ClusterManager.java
  library/src/main/java/com/google/maps/android/clustering/view/DefaultClusterRenderer.java
Labels: cla: yes

#605 Recurse over multi-geometry placemarks
  library/src/main/java/com/google/maps/android/data/kml/KmlRenderer.java
Labels: cla: yes

#614 fix: Make KML/GeoJSON lines and polygons clickable by default
  demo/src/main/res/raw/south_london_square_kml.kml
  library/src/androidTest/java/com/google/maps/android/data/geojson/GeoJsonLineStringStyleTest.java
  library/src/androidTest/java/com/google/maps/android/data/geojson/GeoJsonParserTest.java
  library/src/androidTest/java/com/google/maps/android/data/geojson/GeoJsonPolygonStyleTest.java
  library/src/androidTest/java/com/google/maps/android/data/geojson/GeoJsonRendererTest.java
  library/src/androidTest/java/com/google/maps/android/data/geojson/GeoJsonTestUtil.java
  library/src/androidTest/java/com/google/maps/android/data/kml/KmlParserTest.java
  library/src/androidTest/java/com/google/maps/android/data/kml/KmlRendererTest.java
  library/src/androidTest/java/com/google/maps/android/data/kml/KmlStyleTest.java
  library/src/androidTest/java/com/google/maps/android/data/kml/KmlTestUtil.java
  library/src/main/java/com/google/maps/android/data/Renderer.java
  library/src/main/java/com/google/maps/android/data/Style.java
  library/src/main/java/com/google/maps/android/data/geojson/GeoJsonLineStringStyle.java
  library/src/main/java/com/google/maps/android/data/geojson/GeoJsonPolygonStyle.java
  library/src/main/java/com/google/maps/android/data/kml/KmlStyle.java
Labels: cla: yes
