Repository googlemaps/android-maps-utils, pull requests merged in 2023-01, with the labels that each got.

#767 fix: Apply correction to distanceToLine() measurements
  library/src/main/java/com/google/maps/android/PolyUtil.java
  library/src/test/java/com/google/maps/android/PolyUtilTest.java
Labels: cla: yes

#754 docs: Add long click listener to cluster demo
  demo/src/main/java/com/google/maps/android/utils/demo/ClusteringDemoActivity.java
Labels: cla: yes

#1130 feat: exposing getColor function in the ClusterRenderer
  library/src/main/java/com/google/maps/android/clustering/view/ClusterRenderer.java
  library/src/main/java/com/google/maps/android/clustering/view/DefaultClusterRenderer.java
Labels: type: feature request

#1148 fix: fixed the javadoc task and errors
  build.gradle
  library/src/main/java/com/google/maps/android/clustering/ClusterManager.java
  library/src/main/java/com/google/maps/android/clustering/algo/NonHierarchicalDistanceBasedAlgorithm.java
  library/src/main/java/com/google/maps/android/collections/CircleManager.java
  library/src/main/java/com/google/maps/android/collections/GroundOverlayManager.java
  library/src/main/java/com/google/maps/android/collections/MarkerManager.java
  library/src/main/java/com/google/maps/android/collections/PolygonManager.java
  library/src/main/java/com/google/maps/android/collections/PolylineManager.java
  library/src/main/java/com/google/maps/android/ui/IconGenerator.java
  library/src/main/java/com/google/maps/android/ui/RotationLayout.java
Labels: type: bug, priority: p2

#1143 chore: added nullability annotations
  demo/src/main/java/com/google/maps/android/utils/demo/BaseDemoActivity.java
  demo/src/main/java/com/google/maps/android/utils/demo/CustomMarkerClusteringDemoActivity.java
  demo/src/main/java/com/google/maps/android/utils/demo/DistanceDemoActivity.java
  demo/src/main/java/com/google/maps/android/utils/demo/KmlDemoActivity.java
  demo/src/main/java/com/google/maps/android/utils/demo/SampleManager.java
  demo/src/main/java/com/google/maps/android/utils/demo/model/MyItem.java
  demo/src/main/java/com/google/maps/android/utils/demo/model/Person.java
  library/src/main/java/com/google/maps/android/clustering/ClusterManager.java
  library/src/main/java/com/google/maps/android/clustering/algo/StaticCluster.java
  library/src/main/java/com/google/maps/android/clustering/view/DefaultClusterRenderer.java
  library/src/main/java/com/google/maps/android/collections/CircleManager.java
  library/src/main/java/com/google/maps/android/collections/GroundOverlayManager.java
  library/src/main/java/com/google/maps/android/collections/MarkerManager.java
  library/src/main/java/com/google/maps/android/collections/PolygonManager.java
  library/src/main/java/com/google/maps/android/collections/PolylineManager.java
  library/src/main/java/com/google/maps/android/data/Layer.java
  library/src/main/java/com/google/maps/android/data/LineString.java
  library/src/main/java/com/google/maps/android/data/MultiGeometry.java
  library/src/main/java/com/google/maps/android/data/Point.java
  library/src/main/java/com/google/maps/android/data/Renderer.java
  library/src/main/java/com/google/maps/android/data/geojson/BiMultiMap.java
  library/src/main/java/com/google/maps/android/data/geojson/GeoJsonFeature.java
  library/src/main/java/com/google/maps/android/data/geojson/GeoJsonLayer.java
  library/src/main/java/com/google/maps/android/data/geojson/GeoJsonLineStringStyle.java
  library/src/main/java/com/google/maps/android/data/geojson/GeoJsonPointStyle.java
  library/src/main/java/com/google/maps/android/data/geojson/GeoJsonPolygon.java
  library/src/main/java/com/google/maps/android/data/geojson/GeoJsonPolygonStyle.java
  library/src/main/java/com/google/maps/android/data/geojson/GeoJsonRenderer.java
  library/src/main/java/com/google/maps/android/data/kml/KmlContainer.java
  library/src/main/java/com/google/maps/android/data/kml/KmlGroundOverlay.java
  library/src/main/java/com/google/maps/android/data/kml/KmlMultiGeometry.java
  library/src/main/java/com/google/maps/android/data/kml/KmlPlacemark.java
  library/src/main/java/com/google/maps/android/data/kml/KmlPolygon.java
  library/src/main/java/com/google/maps/android/geometry/Point.java
  library/src/main/java/com/google/maps/android/ui/BubbleDrawable.java
Labels: priority: p2
